### ISSUE TITLE
bluetooth playground upsteam

### ISSUE THREAD

**Issue by Dialgatrainer02** [Keychron/qmk_firmware#207]
### Issue Description

is it possible to upstream bluetooth playground branch or is it stuck on an older qmk release 
 if i cant be up streamed how would you update it locally

**Comment by elfakyn** [comment]
++ing this one. there are bugs in this branch related to RGB state when host suspend/unsuspend (K7 Pro) that are not present in the 1.01 firmware, as well as other different behaviors (happy to file a report, but it does seem to be fixed in the release firmware).

Can we have the code that the K-series keyboards ship with? Thanks!

**Comment by lokher** [comment]
Some Pro keyboards are in `wireless_playground` branch, based on recent upstream.
https://github.com/Keychron/qmk_firmware/tree/wireless_playground/keyboards/keychron

**Comment by Dialgatrainer02** [comment]
thank you so much  wireless playground was exactly what i needed thank you
