### ISSUE TITLE
Issues with Keychron Q3 Pro (ISO Knob Version) Firmware, Bluetooth Connectivity, and Configuration Software

### ISSUE THREAD

**Issue by shm0rt** [Keychron/qmk_firmware#210]
## Problem:
After downloading the firmware from the official website for my Keychron Q3 Pro (ISO Knob version), I've encountered several issues that are affecting the functionality of the keyboard. Initially, the keyboard displayed erratic behavior. While downloading the SE binary seemed to mitigate some problems, the Bluetooth connectivity remains non-functional.

## Additional Issue:
Moreover, the software provided for keyboard configuration is not operating correctly. Despite using a wired connection, which is my usual preference, and attempting to configure the keyboard mappings through the Brave browser on Windows (with all security settings for the site disabled and the browser updated to the newest version), the software fails to recognize the keyboard or allow any mapping changes.

## Impact:
These issues are particularly concerning given the substantial investment made into this keyboard, amounting to several hundred euros. The expected functionality and support for a device of this caliber are not met, leading to a disappointing user experience.

## Request:
Could you please provide assistance, updates, or workarounds to address these problems? Any guidance on how to resolve the Bluetooth connectivity and software configuration issues would be greatly appreciated.

Thank you for your attention to this matter.

**Comment by PeterMortensen** [comment]
Re *"the software provided for keyboard configuration is not operating correctly"*: It ***doesn't*** work in any browser (for instance, [Firefox](https://en.wikipedia.org/wiki/Mozilla_Firefox)). A particular feature ([declared harmful](https://www.reddit.com/r/MechanicalKeyboards/comments/vvvvpr/comment/ifno27q/) by Mozilla) must be enabled in the web browser. [Google Chrome](https://en.wikipedia.org/wiki/Google_Chrome) and [Edge](https://en.wikipedia.org/wiki/Microsoft_Edge) (in sufficiently new versions) are known to work (there are probably others).

An assumption was made that everybody uses Google Chrome (without telling anybody about the assumption). That is not the case; the assumption is false.

Here are [some alternatives](https://www.reddit.com/r/Keychron/comments/1c8z158/comment/l0jreph/). None of them are free of either 1) the need to download a supplementary (JSON) file for the Q3 Pro (the Google Chrome + Via combination requires that as well), 2) use one of the compatible browsers, or 3) change QMK source files and compile. The [stand-alone Via application](https://github.com/the-via/releases/releases) may be the least questionable, though it is a [Chromium](https://en.wikipedia.org/wiki/Chromium_(web_browser)) browser in disguise and ***[requires](https://www.reddit.com/r/Keychron/comments/18hikn3/comment/kd7gk75/)*** an Internet connection to work.

As for the Bluetooth connectivity problems, it may indeed be something that could be fixed in the QMK firmware. But here are [some tips](https://www.reddit.com/r/Keychron/comments/1cawaxb/comment/l0yaqje/) that doesn't require firmware changes.
