### ISSUE TITLE
[Feature Request] K6 PRO New auto sleep treshold

### ISSUE THREAD

**Issue by mathgonzlez** [Keychron/qmk_firmware#254]
### Feature Request Type

- [X] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [X] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

### Description

Hi,

I suggest adding more predefined auto sleep thresholds, like 2 and 5 minutes. I often use the keyboard in an audio studio environment, where I might use certain shortcuts and then leave the keyboard unused for extended periods, sometimes up to 20 minutes. Having the keyboard enter standby mode after 2 minutes instead of 10 could significantly improve battery life. Do you think it's possible to implement this change?

Thanks

**Comment by PeterMortensen** [comment]
Workaround: [Change](https://www.reddit.com/r/Keychron/comments/1bxzfpo/comment/kygm4lc/) the default 10 minutes to some other value. Change the line with `CONNECTED_BACKLIGHT_DISABLE_TIMEOUT`. The unit is seconds and the default value is 600 (10 minutes).

For example, to 2 minutes:

    #define CONNECTED_BACKLIGHT_DISABLE_TIMEOUT 120

Note the ***illogical*** naming. There may or may not be an internal renaming some time in the future (or perhaps (effectively a renaming) by a fix of the implementation using CONNECTED_BACKLIGHT_DISABLE_TIMEOUT). The value of the more logical DISCONNECTED_BACKLIGHT_DISABLE_TIMEOUT only applies right after powerup... (that is, only for the very first sleep, not subsequent sleeps...) This is my empirical knowledge from a K10 Pro from earlier this year (it may have been fixed in the meantime, but I doubt it).
